app/Console/Commands/RunUpdate.php
This PR will add the `queue:restart` command to the Update Class.
=> feat(RunUpdate): add queue:restart command to update

requirements.txt
Reverts Status-Page/Status-Page#434
=> revert: chore(deps): bump markdown from 3.3.7 to 3.4.1

docs/release-notes/version-2.1.md, statuspage/subscribers/models.py
=> fix: subscriber verification mail

docs/release-notes/version-2.1.md, statuspage/templates/base/home.html
=> fix: custom header/footer html char escaping

docs/release-notes/version-2.1.md, statuspage/maintenances/forms/models.py
=> fix: maintenance update textbox

statuspage/utilities/templatetags/helpers.py
=> fix: incident and maintenance template urlencode

statuspage/templates/incidents/incidenttemplate.html, statuspage/templates/maintenances/maintenancetemplate.html
=> fix: incident and maintenance template char-escaping

docs/release-notes/version-2.2.md, statuspage/incidents/forms/models.py, statuspage/incidents/urls.py, statuspage/incidents/views.py, statuspage/maintenances/forms/models.py, statuspage/maintenances/urls.py, statuspage/maintenances/views.py, statuspage/statuspage/views/generic/base.py, statuspage/templates/incidents/incident_create.html, statuspage/templates/incidents/incidenttemplate.html, statuspage/templates/maintenances/maintenance_create.html, statuspage/templates/maintenances/maintenancetemplate.html, statuspage/utilities/templates/form_helpers/render_field.html
=> feat: template selector

statuspage/incidents/signals.py, statuspage/maintenances/signals.py, statuspage/subscribers/models.py, statuspage/utilities/utils.py
finally, my inbox get's clogged up less
=> fix: mail threading

docs/release-notes/version-2.2.md, statuspage/incidents/signals.py, statuspage/maintenances/signals.py
=> fix: incident / maintenance creation emails not sent

statuspage/incidents/signals.py, statuspage/maintenances/signals.py, statuspage/templates/emails/incidents/created.html, statuspage/templates/emails/incidents/created.txt, statuspage/templates/emails/maintenances/created.html, statuspage/templates/emails/maintenances/created.txt
=> fix: send one incident and maintenance creation mail

statuspage/templates/emails/incidents/created.html, statuspage/templates/emails/incidentupdates/created.html, statuspage/templates/emails/maintenances/created.html, statuspage/templates/emails/maintenanceupdates/created.html
=> fix: markdown rendering for update emails

statuspage/extras/admin.py, statuspage/statuspage/config/parameters.py, statuspage/statuspage/views/__init__.py, statuspage/templates/home.html
=> fix: hide recent updates when empty

statuspage/incidents/api/serializers.py, statuspage/maintenances/api/serializers.py
=> fix: api docs

statuspage/incidents/signals.py, statuspage/maintenances/signals.py
=> fix: duplicate email message ids

statuspage/incidents/tables.py, statuspage/maintenances/tables.py, statuspage/statuspage/tables/columns.py
=> fix: cut update text off

statuspage/utilities/templatetags/helpers.py
=> fix: impact typo

statuspage/incidents/signals.py, statuspage/maintenances/signals.py
=> fix: surround message id headers with <brackets>

docs/release-notes/version-2.2.md, statuspage/templates/base/layout_email.html, statuspage/templates/emails/components/update.html, statuspage/templates/emails/incidents/created.html, statuspage/templates/emails/incidentupdates/created.html, statuspage/templates/emails/maintenances/created.html, statuspage/templates/emails/maintenanceupdates/created.html, statuspage/templates/emails/subscribers/management-key.html, statuspage/templates/emails/subscribers/verification.html
=> fix: update all email templates

requirements.txt
=> fix: django-rq not finding rq_scheduler

docs/important-notes/admin-panel.md, mkdocs.yml, statuspage/templates/base/dashboard.html
=> docs: document admin panel 2fa behaviour

statuspage/components/api/nested_serializers.py, statuspage/components/api/serializers.py, statuspage/incidents/api/nested_serializers.py, statuspage/incidents/api/serializers.py, statuspage/maintenances/api/nested_serializers.py, statuspage/maintenances/api/serializers.py, statuspage/metrics/api/nested_serializers.py, statuspage/metrics/api/serializers.py, statuspage/subscribers/api/serializers.py
=> fix: add created and last_updated fields

statuspage/subscribers/forms/models.py
=> fix: subscriber without email verification

docs/release-notes/version-2.2.md, statuspage/utilities/templatetags/helpers.py
=> fix: historic incident date

statuspage/components/views.py, statuspage/incidents/views.py, statuspage/maintenances/views.py, statuspage/metrics/views.py, statuspage/sp_external_status_providers/views.py, statuspage/subscribers/views.py
=> fix: model creation

statuspage/extras/signals.py
Here is a correction for anonymous people who want to subscribe and not be able to logged in dashboard
Linked with issue #588
=> fix: anonymous subscribers - signals.py
